# Generated by Django 3.1.3 on 2020-11-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=255, verbose_name='Концепт')),
                ('interpretation', models.TextField(verbose_name='Толкование')),
            ],
            options={
                'verbose_name': 'Глосса',
                'verbose_name_plural': 'Глоссарий',
            },
        ),
    ]
